openshift/whereabouts-cni

- README.md
- doc/daemonset-install.yaml
- doc/whereabouts.cni.cncf.io_ippools.yaml
- go.mod
- pkg/api/v1alpha1/groupversion_info.go
Correctly sets the whereabouts CRD namespace, given input from Weibin in this pastebin @ http://pastebin.test.redhat.com/843561
> Updates CRD name to whereabouts.cni.cncf.io

- README.md
- doc/daemonset-install.yaml
- doc/whereabouts.cni.cncf.io_ippools.yaml
- go.mod
- pkg/api/v1alpha1/groupversion_info.go
> Updates CRD name to whereabouts.cni.cncf.io [backport 4.3.z]

- OWNERS
- README.md
- cmd/whereabouts_test.go
- go.mod
- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Big thanks Aneesh! Has fixes for BZ 1836405 to exclude the network address, and includes thorough testing.
Additionally includes commit for changes to `range_end should be treated as inclusive when iterating for ip assignments`
> Bug 1836405: Updates for excluding network address

- cmd/whereabouts.go
- pkg/storage/storage.go
This changes change error message in case of kubeconfig non-existence
at loading IPAM config to cause appropreate error message when kubeconfig
is not exist in case of kubernetes CRD mode.
> Change error message (for kubeconfig missing failure)

- cmd/whereabouts_test.go
- pkg/storage/kubernetes.go
This applies only to OCP 4.5, as this is fixed in 4.6 during an enhancement.
> Bug 1877065: Fixing wrong DNS-1123 name for some IPv6 addresses

- cmd/whereabouts.go
- pkg/storage/storage.go
This changes change error message in case of kubeconfig non-existence
at loading IPAM config to cause appropreate error message when kubeconfig
is not exist in case of kubernetes CRD mode.
> Bug 1868772: [backport 4.5] Change error message (for missing kubeconfig)

- Dockerfile.openshift
Updating ose-multus-whereabouts-ipam-cni builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/ose-multus-whereabouts-ipam-cni.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
> Bug 1878163: Updating ose-multus-whereabouts-ipam-cni builder & base images to be consistent with ART

- cmd/whereabouts_test.go
- pkg/allocate/allocate.go
Excluded subnets was handled for ipv4. This fix handles ipv6 as well.
Adds test to check for excluding IPv6 addresses
As reported in: dougbtv/whereabouts#71
> Excluded subnet handling for ipv6

- cmd/whereabouts.go
See: https://github.com/dougbtv/whereabouts/issues/70
> Bug 1898670: Removes error when deallocating IP errors out, instead just warns

- cmd/whereabouts.go
> Bug 1898672: Removes error when deallocating IP errors out, instead just warns [backport 4.6]

- cmd/whereabouts_test.go
- pkg/allocate/allocate.go
Excluded subnets was handled for ipv4. This fix handles ipv6 as well.
Adds test to check for excluding IPv6 addresses
> Bug 1898616: Excluded subnet handling for ipv6 [backport 4.6]

- pkg/config/config.go
- pkg/storage/kubernetes/ipam.go
- pkg/types/types.go
Updates sleep_for_race parameter so we can use it in e2e tests and specify the sleep amount.
> Configurable sleep_for_race parameter

- cmd/reconciler/ip.go
- doc/crds/ip-reconciler-job.yaml
This is a WIP intended to see how much this impacts CI for the moment. 
Generally has a set of known errors that cause the reconciler to exit 0 when they're detected.
> Bug 2050409: ip-reconciler should have known errors from api server on instantiation

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
* prevent iterating complete excluded ranges
* Fix allocation test for large range skipping, err unused reported by staticcheck
* skip ranges >2 mask length
* Added unit tests for large ranges and unsorted ranges
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Co-authored-by: Bram Verschueren <verschueren.bram@gmail.com>
Co-authored-by: dougbtv <dosmith@redhat.com>
> OCPBUGS-2948: Excluded ranges bug (#282)

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
* prevent iterating complete excluded ranges
* Fix allocation test for large range skipping, err unused reported by staticcheck
* skip ranges >2 mask length
* Added unit tests for large ranges and unsorted ranges
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Co-authored-by: Bram Verschueren <verschueren.bram@gmail.com>
Co-authored-by: dougbtv <dosmith@redhat.com>
> OCPBUGS-3941: Backport Excluded ranges bug (#282)

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
* prevent iterating complete excluded ranges
* Fix allocation test for large range skipping, err unused reported by staticcheck
* skip ranges >2 mask length
* Added unit tests for large ranges and unsorted ranges
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Co-authored-by: Bram Verschueren <verschueren.bram@gmail.com>
Co-authored-by: dougbtv <dosmith@redhat.com>
> OCPBUGS-3942: Excluded ranges bug (#282)

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
* prevent iterating complete excluded ranges
* Fix allocation test for large range skipping, err unused reported by staticcheck
* skip ranges >2 mask length
* Added unit tests for large ranges and unsorted ranges
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
Co-authored-by: Bram Verschueren <verschueren.bram@gmail.com>
Co-authored-by: dougbtv <dosmith@redhat.com>
> OCPBUGS-3943: Excluded ranges bug (#282)

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
This prevent overflowing outside the requested `ipam.range` when excluding ranges while the requested range is exhausted.
Also corrects a test where we expected to assign an IP outside of the expected range.
> OCPBUGS-11324: respect requested allocation range when exluding ranges [backport 4.14]

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
This prevent overflowing outside the requested ipam.range when excluding ranges while the requested range is exhausted.
Also corrects a test where we expected to assign an IP outside of the expected range.
> OCPBUGS-11322: respect requested allocation range when exluding ranges [Backport 4.13]

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
This prevent overflowing outside the requested ipam.range when excluding ranges while the requested range is exhausted.
Also corrects a test where we expected to assign an IP outside of the expected range.
> OCPBUGS-11321: respect requested allocation range when exluding ranges [Backport 4.12]

- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
This prevent overflowing outside the requested `ipam.range` when excluding ranges while the requested range is exhausted.
Also corrects a test where we expected to assign an IP outside of the expected range.
> OCPBUGS-11067: respect requested allocation range when exluding ranges [backport 4.11]

- Dockerfile.openshift
Now that the binary is being dynamically compiled downstream, the binary must match the RHEL version of RHCOS because it is copied to the host.
> Restores RHEL specific binary copy and updates to rhel9/8

- Dockerfile.openshift
OCP4.13 container image is RHEL8 based image, so need to change default binary in /usr/src/whereabous/bin to RHEL8.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer** *(optional)*:
> Bug 16002: Change default binary to RHEL8 image

- pkg/reconciler/iploop.go
> OCPBUGS-15905: Denormalize IP name before checking if pod is alive [Backport 4.14]

- pkg/reconciler/iploop.go
> OCPBUGS-5954: Denormalize IP name before checking if pod is alive [Backport 4.11]

- pkg/reconciler/iploop.go
> OCPBUGS-5955: Denormalize IP name before checking if pod is alive [Backport 4.10]

- doc/crds/daemonset-install.yaml
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/reconciler/wrappedPod.go
- pkg/storage/kubernetes/client.go
- pkg/storage/storage.go
This fix resolves the issue where, after a forceful node reboot, force deleting a pod in a stateful set causes the pod to be recreated and remain indefinitely in the Pending state.
Solution description, as written on xagent003's [upstream PR](https://github.com/k8snetworkplumbingwg/whereabouts/pull/195):
"We shouldn't treat all pending Pods as "alive" and skip the check. The list of all Pods fetch'd earlier may be stale, and as observed in some scenarios, several seconds before the ip-reconciler does the isPodAlive check.
Instead, can we retry a Get on an individual Pod, with the hopes that it has final IP/network annoations? So we try to refetch the pod a few times if it is Pending state and initial IP check fails. After that, just do the IP matching check like before"
Note that …
> OCPBUGS-18893: Rechecking pending Pods (conflict resolved)

- doc/crds/daemonset-install.yaml
- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/reconciler/wrappedPod.go
- pkg/storage/kubernetes/client.go
- pkg/storage/storage.go
Backports 3 commits to fix the assignment error from #228 and #196
> OCPBUGS-26553: Cherry pick fix assignment 4.14

- doc/crds/daemonset-install.yaml
- pkg/allocate/allocate.go
- pkg/allocate/allocate_test.go
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/reconciler/wrappedPod.go
- pkg/storage/kubernetes/client.go
- pkg/storage/storage.go
Backports the "stuck in ContainerCreating state" bug, cherry-picked from:
https://github.com/openshift/whereabouts-cni/pull/230
Note: the only conflicts were on `pkg/allocate/allocate.go` the following var names 
were modified: firstip, lastip, reservelist
> OCPBUGS-27367: [release-4.13] Backport fix assignment

- cmd/whereabouts.go
- pkg/allocate/allocate.go
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/storage/kubernetes/ipam.go
Manual cherry-pick of https://github.com/openshift/whereabouts-cni/pull/284
Only commits to solve OCPBUGS-24663 are included.
> OCPBUGS-34929: [release-4.16] Use IP to identify orphaned allocation to be deleted

- cmd/whereabouts.go
- pkg/allocate/allocate.go
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/storage/kubernetes/ipam.go
Manual cherry-pick of https://github.com/openshift/whereabouts-cni/pull/284
Only commits to solve OCPBUGS-24663 are included.
> OCPBUGS-35081: [release-4.15] Use IP to identify orphaned allocation to be deleted

- cmd/whereabouts_test.go
- e2e/e2e_test.go
- pkg/controlloop/pod.go
- pkg/reconciler/ip.go
- pkg/reconciler/ip_test.go
- pkg/reconciler/iploop.go
- pkg/reconciler/wrappedPod.go
- pkg/storage/kubernetes/client.go
- pkg/storage/kubernetes/ipam.go
Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/303
Only commits to fix [OCPBUGS-33941](https://issues.redhat.com/browse/OCPBUGS-33941) and [OCPBUGS-29664](https://issues.redhat.com/browse/OCPBUGS-29664)
> OCPBUGS-37707,OCPBUGS-37708: [release-4.16] align api calls timeout and skip pods marked for deletion

- Dockerfile.test.openshift
To run e2e tests in prow cluster we need the entire whereabouts binary in the final image build. we want to add a dockerfile just for testing that we can use here that we dont use anywhere else since it takes the image size from ~600mb to ~1gb
C @dougbtv
> NP-1108: <Carry> Add test dockerfile

- Dockerfile.test.openshift
To run e2e tests in prow cluster we need the entire whereabouts binary in the final image build. we want to add a dockerfile just for testing that we can use here that we dont use anywhere else since it takes the image size from ~600mb to ~1gb
> <Carry> OCPBUGS-45854: Add test dockerfile

- Dockerfile.openshift
- hack/build-go.sh
To run e2e tests in prow cluster we need the entire whereabouts binary in the final image build. we want to add a dockerfile just for testing that we can use here that we dont use anywhere else since it takes the image size from ~600mb to ~1gb
rename dockerfile dirs to point to openshift instead of k8snetworkplumbingwg
> NP-1110: <Carry> Add test dockerfile

- Makefile
- hack/test-go.sh
Move go vet into skip static, go vet does not have permission to run in the ci cluster, which is where we call the make test-skip-static
> NP-1110: Allow go vet to be skipped

- script/install-cni.sh
Creates functions to generate the kubeconfig and whereabouts conf use these functions to check if the serviveAccount changes to regen the kubeconfig if it expires
Change WHEREABOUTS_FLATFILE to WHEREABOUTS_CONF_FILE for clarity
Signed-off-by: Benjamin Pickard <bpickard@redhat.com>
(cherry picked from commit 27fd922b1521dac11adc7b5aa4bd057675822cc8)
> OCPBUGS-48745: [Release-4.17]Kubeconfig loop

- Dockerfile.openshift
I removed the entrypoint from the dockerfile when adding node-slice-controller, this adds it back
cc @dougbtv
> OCPBUGS-52415: replace entrypoint

- Dockerfile.openshift
We need the nodeSliceController binary in the openshift dockerfile to allow the whereabouts controller to be built
> OCPBUGS-58360: Add nodeslicecontroller bin to dockerfile
