openshift/whereabouts-cni

README.md
doc/daemonset-install.yaml
doc/whereabouts.cni.cncf.io_ippools.yaml
go.mod
pkg/api/v1alpha1/groupversion_info.go

Bug 1813031: Updates CRD name to whereabouts.cni.cncf.io [backport 4.4]

---

cmd/reconciler/ip.go
cmd/reconciler/ip_test.go
pkg/reconciler/iploop.go
pkg/reconciler/iploop_test.go
pkg/reconciler/wrappedPod.go
pkg/storage/kubernetes/client.go
pkg/storage/kubernetes/ipam.go

Almost includes changes for reconciling pods in pending phase, and contexts cleanup as they conflicted during cherry-pick

Bug 2065785: Sync upstream for context improvements

---

pkg/reconciler/wrappedPod.go
pkg/reconciler/wrappedPod_test.go

@dougbtv  as requested this is the new pull request.

ip-reconciler: Add all non default interfaces to Pod IP list

---

pkg/reconciler/ip_test.go
pkg/reconciler/wrappedPod.go
pkg/reconciler/wrappedPod_test.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer** *(optional)*:
clean cherry-pick

[release-4.13] OCPBUGS-11427: Fix network status annotation to k8s.v1.cni.cncf.io/network-status

---

pkg/storage/kubernetes/ipam.go

What this PR does / why we need it:
ipv6 ranges ending in a colon, such as a trail of zeroes denoted by "::" result in the storage engine failing to process the range, because ranges are expected to begin and end with alphanumerical characters to meet CRD requirements. Thus we append a 0 to any ranges that meet this criteria because it is functionally equivalent and meets the requirements.
Signed-off-by: nicklesimba [simha.nikhil@gmail.com](mailto:simha.nikhil@gmail.com)

OCPBUGS-7429: Invalid ipv6 backport 4.12

---

pkg/storage/kubernetes/ipam.go

What this PR does / why we need it:
ipv6 ranges ending in a colon, such as a trail of zeroes denoted by "::" result in the storage engine failing to process the range, because ranges are expected to begin and end with alphanumerical characters to meet CRD requirements. Thus we append a 0 to any ranges that meet this criteria because it is functionally equivalent and meets the requirements.

OCPBUGS-13241: Added trailing 0 to ipv6 ranges that end in ":" [Backport 4.11]

---

pkg/storage/kubernetes/ipam.go

ipv6 ranges ending in a colon, such as a trail of zeroes denoted by "::" result in the storage engine failing to process the range, because ranges are expected to begin and end with alphanumerical characters to meet CRD requirements. Thus we append a 0 to any ranges that meet this criteria because it is functionally equivalent.

OCPBUGS-13242: Added trailing 0 to ipv6 ranges that end in ":" [Backport 4.10]

---

Dockerfile.openshift
entrypoint.sh

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer** *(optional)*:

Bug 16136: Introduce entrypoint.sh to call ip-control-loop based on RHEL ver

---

pkg/reconciler/iploop.go

OCPBUGS-4417: Denormalize IP name before checking if pod is alive [Backport 4.13]

---

pkg/reconciler/iploop.go

OCPBUGS-5953: Denormalize IP name before checking if pod is alive [Backport 4.12]

---

pkg/allocate/allocate.go
pkg/allocate/allocate_test.go
pkg/reconciler/ip_test.go

Downstream sync for December 2023

OCPBUGS-24608: Downstream sync - includes assignment error fix

---

pkg/allocate/allocate.go
pkg/allocate/allocate_test.go

Backports 2 commits with the assignment error fix from https://github.com/openshift/whereabouts-cni/pull/211

OCPBUGS-18893: Assignment error fix

---

doc/crds/daemonset-install.yaml
pkg/allocate/allocate.go
pkg/allocate/allocate_test.go
pkg/reconciler/ip_test.go
pkg/reconciler/iploop.go
pkg/reconciler/wrappedPod.go
pkg/storage/kubernetes/client.go
pkg/storage/storage.go

Backports the "stuck in ContainerCreating state" bug, cherry-picked from: #236

OCPBUGS-16008: Cherry pick fix assignment 4.12

---

.snyk

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer** *(optional)*:

OCPBUGS-32931: Add .snyk file

---

OWNERS

removes stale owners and adds myself and peng
@dougbtv @zshi-redhat

NP-1045:Update owners

---

.gitignore
cmd/whereabouts.go
cmd/whereabouts_test.go
doc/crds/whereabouts.cni.cncf.io_ippools.yaml
doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
e2e/client/replicaset.go
e2e/e2e_test.go
e2e/poolconsistency/checker.go
e2e/poolconsistency/poolconsistency_test.go
e2e/retrievers/pod.go
pkg/allocate/allocate.go
pkg/allocate/allocate_test.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/ippool_types.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation_types.go
pkg/storage/kubernetes/ipam.go
pkg/storage/storage.go
pkg/types/types.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/293

OCPBUGS-36367: [release-4.15] Return previous IP allocation for add cmd

---

.github/workflows/image-build.yml
.github/workflows/image-push-master.yml
.github/workflows/image-push-release.yml
cmd/whereabouts_test.go
e2e/e2e_test.go
pkg/controlloop/pod.go
pkg/reconciler/ip.go
pkg/reconciler/ip_test.go
pkg/reconciler/iploop.go
pkg/reconciler/wrappedPod.go
pkg/storage/kubernetes/client.go
pkg/storage/kubernetes/ipam.go

OCPBUGS-33941: upstream sync 23072024

---

.gitignore
cmd/whereabouts.go
cmd/whereabouts_test.go
doc/crds/whereabouts.cni.cncf.io_ippools.yaml
doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
e2e/client/replicaset.go
e2e/e2e_test.go
e2e/poolconsistency/checker.go
e2e/poolconsistency/poolconsistency_test.go
e2e/retrievers/pod.go
pkg/allocate/allocate.go
pkg/allocate/allocate_test.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/ippool_types.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation_types.go
pkg/reconciler/ip_test.go
pkg/reconciler/iploop.go
pkg/storage/kubernetes/ipam.go
pkg/storage/storage.go
pkg/types/types.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/289 and https://github.com/openshift/whereabouts-cni/pull/296

OCPBUGS-37944,OCPBUGS-37941: [release-4.13] Stateful fixes

---

.gitignore
cmd/whereabouts.go
cmd/whereabouts_test.go
doc/crds/whereabouts.cni.cncf.io_ippools.yaml
doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
e2e/client/replicaset.go
e2e/e2e_test.go
e2e/poolconsistency/checker.go
e2e/poolconsistency/poolconsistency_test.go
e2e/retrievers/pod.go
pkg/allocate/allocate.go
pkg/allocate/allocate_test.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/ippool_types.go
pkg/api/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation_types.go
pkg/reconciler/ip_test.go
pkg/reconciler/iploop.go
pkg/storage/kubernetes/ipam.go
pkg/storage/storage.go
pkg/types/types.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/306

OCPBUGS-38019,OCPBUGS-37942: [release-4.12] Stateful fixes

---

.github/workflows/chart-push-release.yml
.github/workflows/test.yml
Dockerfile
Dockerfile.arm64
Makefile
README.md
deployment/whereabouts-chart/Chart.yaml
deployment/whereabouts-chart/crds/whereabouts.cni.cncf.io_ippools.yaml
deployment/whereabouts-chart/crds/whereabouts.cni.cncf.io_nodeslicepools.yaml
deployment/whereabouts-chart/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
deployment/whereabouts-chart/templates/NOTES.txt
deployment/whereabouts-chart/templates/_helpers.tpl
deployment/whereabouts-chart/templates/cluster_role.yaml
deployment/whereabouts-chart/templates/cluster_role_binding.yaml
deployment/whereabouts-chart/templates/configmap.yaml
deployment/whereabouts-chart/templates/daemonset.yaml
deployment/whereabouts-chart/templates/node-slice-controller.yaml
deployment/whereabouts-chart/templates/serviceaccount.yaml
deployment/whereabouts-chart/values.yaml
hack/generate-code.sh
hack/release/chart-push.sh
hack/release/chart-update.sh
pkg/reconciler/iploop.go

Downstream merge for whereabouts oct 10, 2024
cc @dougbtv @pliurh 
Please add bug numbers to title if you need to

OCPBUGS-33946: Ds merge 10/9/24

---

Dockerfile.openshift

Adds node-slice-controller package to packages built in the dockerfile, we need this to enable fast ranges

NP-1100: Add nodeslicecontroller to dockerfile

---

.github/dependabot.yml
.github/workflows/test.yml
Dockerfile
Dockerfile.arm64
pkg/node-controller/controller.go
pkg/types/types.go

ds merge w controller watcher fix for nads without ip-range for fast ranges

OCPBUGS-54422: Ds merge 4/3

---

pkg/controlloop/pod.go
pkg/storage/kubernetes/ipam.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/353
Upstream commit https://github.com/k8snetworkplumbingwg/whereabouts/pull/556

OCPBUGS-55270: Fix whereabouts-reconciler no namespace error

---

pkg/controlloop/pod.go
pkg/storage/kubernetes/ipam.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/362

OCPBUGS-55617: Fixes leftover podref issue

---

pkg/controlloop/pod.go
pkg/storage/kubernetes/ipam.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/364

OCPBUGS-55618: Fixes leftover podref issue

---

pkg/controlloop/pod.go
pkg/storage/kubernetes/ipam.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/365

[release-4.15] OCPBUGS-55619: Fixes leftover podref issue

---

pkg/controlloop/pod.go
pkg/storage/kubernetes/ipam.go

Manual cherry-pick https://github.com/openshift/whereabouts-cni/pull/366

[release-4.14] OCPBUGS-55620: Fixes leftover podref issue
